contember/docs

- docs/intro/quickstart.mdx
> Quickstart: Add quotes around @contember

- docs/guides/deploy-contember.md
Small updates to easily set up Contember Cloud deployment.
Will require more work when we'll launch Cloud publicly.
> Update deployment to Cloud description

- docs/intro/quickstart.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/56)
> quickstart: use lazy page pattern

- docs/guides/self-hosted-contember.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/58)
> fix: update scaling section for self-hosted setup

- docs/reference/admin/components/_content/BlockEditor.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/59)
> Reference BlockEditor: Fix schema example

- src/index.sass
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/62)
> fix mobile width

- docs/workshop.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/66)
> add workshop page

- docs/reference/engine/tenant/overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/68)
> tenant better introduction

- docs/reference/engine/schema/migrations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/70)
> Migrations typo

- docs/reference/engine/schema/relationships.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/71)
> Relationships nullability anchor fix

- docs/reference/engine/schema/migrations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/79)
> migrations: add skippedErrors

- docs/reference/engine/content/advanced/assume-identity.md
- docs/reference/engine/content/advanced/assume-membership.md
- docs/reference/engine/content/advanced/caching.md
- docs/reference/engine/content/advanced/request-debugging.md
- docs/reference/engine/schema/acl.md
- sidebars.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/78)
> advanced content api features

- docs/reference/engine/content/transfer.md
- sidebars.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/82)
> data transfer cli docs

- docs/reference/engine/schema/columns.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/84)
> improve columns chapter

- .github/workflows/publish.yml
Cloudflare pages app is not working for PRs from forked repositories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/86)
> Create action for publish to cloudflare pages

- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/87)
> Add name for publish action

- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/88)
> Add build to publish action

- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/89)
> Run publish action on push to main branch

- docs/reference/engine/content/overview.md
- docs/reference/engine/content/queries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/85)
> improve queries chapter

- .github/workflows/check.yaml
- .github/workflows/deploy.yaml
- docs/reference/admin/theming/pallettes.mdx
- package-lock.json
- src/theming/Components/GeneratorLazy.tsx
- src/theming/Components/Scale.tsx
- src/theming/Components/index.ts
Cc. @HongAnhNemRan, @LukasChalupa
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/docs/81)
> Reintroduce palette generator

- README.md
- docker-compose.override.dist.yaml
- docker-compose.yaml
- docs/intro/quickstart.mdx
- docs/reference/admin/layouts/_Example/components/Directives.tsx
- docs/reference/admin/layouts/_Example/components/Layout.tsx
- docs/reference/admin/layouts/_Example/components/Slots.ts
- docs/reference/admin/layouts/_Example/index.tsx
- docs/reference/admin/layouts/_Example/my-custom-layout.tsx
- docs/reference/admin/layouts/_Example/pages/example.tsx
- docs/reference/admin/layouts/custom-layouts.mdx
- docs/reference/admin/layouts/directives.mdx
- docs/reference/admin/layouts/overview.mdx
- docs/reference/admin/layouts/providers.mdx
- docs/reference/admin/layouts/slots.mdx
- docs/tsconfig.json
- package-lock.json
- package.json
- sidebars.js
- src/tsconfig.json
- tsconfig.json
See online: https://pr-new-layout.docs-dwe.pages.dev/reference/admin/layouts/overview
> New layout: Slots & Directives

- docs/reference/engine/actions/overview.md
Several people encountered this so I figure it's good idea to add this:
> Add warning note about upgrading to new version
